name: Model Request 
description: Request a model to be included in the hub
title: "Model Request: "
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: "Thank you for taking the time to file a Feature Request report."
  - type: input
    attributes:
      label: Model Title
      description: "Suggest a title for your model (e.g. 'Antimicrobial activity prediction')"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Publication
      description: "Is there a link to a publication? (DOI, PMID, URL...)?"
  - type: textarea
    attributes:
      label: Code
      description: "Is code available? If so, please provide link to repository (GitHub, GitLab, BitBucket...)?"
